import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type LangCode = "en" | "ar" | "es" | "bs" | "no";

export const LANGUAGES: Record<LangCode, { label: string; nativeLabel: string; flag: string; rtl: boolean }> = {
  en: { label: "English",   nativeLabel: "English",   flag: "🇬🇧", rtl: false },
  ar: { label: "Arabic",    nativeLabel: "العربية",   flag: "🇦🇪", rtl: true  },
  es: { label: "Spanish",   nativeLabel: "Español",   flag: "🇪🇸", rtl: false },
  bs: { label: "Bosnian",   nativeLabel: "Bosanski",  flag: "🇧🇦", rtl: false },
  no: { label: "Norwegian", nativeLabel: "Norsk",     flag: "🇳🇴", rtl: false },
};

const EN = {
  dashboard:          "Dashboard",
  jobs:               "Jobs",
  timeRecord:         "Time Record",
  supervision:        "Live Supervision",
  technicians:        "Technicians",
  workshop:           "Workshop",
  stages:             "Stages",
  clockIn:            "Clock In",
  clockOut:           "Clock Out",
  startShift:         "Start Shift",
  endShift:           "End Shift",
  save:               "Save",
  cancel:             "Cancel",
  logout:             "Logout",
  export:             "Export",
  assign:             "Assign",
  reassign:           "Reassign",
  addNote:            "Add Note",
  notes:              "Notes",
  tasks:              "Tasks",
  inspections:        "Inspections",
  parts:              "Parts",
  subject:            "Subject",
  attachment:         "Attachment",
  notifications:      "Notifications",
  assignedJobs:       "Assigned Jobs",
  jobManagement:      "Job Management",
  allJobs:            "All",
  newJobs:            "New",
  onHoldJobs:         "On Hold",
  doneJobs:           "Done",
  unassigned:         "Unassigned",
  assignJob:          "Assign Job",
  viewAllJobs:        "View All Jobs",
  putOnHold:          "Put On Hold",
  resumeJob:          "Resume Job",
  moveTo:             "Move to",
  advanceStage:       "Advance Stage",
  awaitingQC:         "All tasks done — advancing stage",
  allTasksDoneQC:     "All tasks done — awaiting QC approval",
  qcRequired:         "QC Required",
  qcManual:           "Quality check — supervisor must approve before advancing",
  stageComplete:      "Final stage reached — ready to complete job",
  pending:            "Pending",
  inProgress:         "In Progress",
  onHold:             "On Hold",
  completed:          "Completed",
  done:               "Done",
  pass:               "Pass",
  fail:               "Fail",
  reception:          "Reception",
  diagnosis:          "Diagnosis",
  repair:             "Repair",
  qcCheck:            "QC Check",
  readyForDelivery:   "Ready for Delivery",
  totalHours:         "Total Hours",
  productivity:       "Productivity",
  workedHours:        "Worked",
  estimatedHours:     "Est. Hours",
  efficiency:         "Efficiency",
  vehicle:            "Vehicle",
  licensePlate:       "License Plate",
  serviceAdvisor:     "Service Advisor",
  odometer:           "Odometer",
  customerNotes:      "Customer Notes",
  laborType:          "Labor Type",
  attendance:         "Attendance",
  search:             "Search",
  takeAction:         "Take Action",
  language:           "Language",
  settings:           "Settings",
  workshopLoading:    "Workshop Loading",
  technicianLoad:     "Technician Load",
  jobPipeline:        "Job Pipeline",
  team:               "Team",
  capacity:           "Capacity",
  criticalAlerts:     "Critical Alerts",
  capacityWarnings:   "Capacity Warnings",
  fullyBooked:        "Fully Booked",
  nearlyFull:         "Nearly Full",
  available:          "Available",
  busy:               "Busy",
  delayed:            "Delayed",
  overdue:            "Overdue",
  today:              "Today",
  week:               "Week",
  month:              "Month",
  noJobs:             "No jobs",
  signIn:             "Sign In",
  welcome:            "Welcome",
  myWorkingPattern:   "My Working Pattern",
  activeJobs:         "Active Jobs",
  openJobs:           "Open Jobs",

  attention:          "Attention",
  estimator:          "Estimator",
  estimates:          "Estimates",
  estimate:           "Estimate",
  estimateNo:         "Estimate No.",
  beginInspection:    "Begin Inspection",
  aiDamageAnalysis:   "AI Damage Analysis",
  takePhoto:          "Take Photo",
  retakePhoto:        "Retake Photo",
  analysingDamage:    "Analysing Damage...",
  damageDescription:  "Damage Description",
  laborLines:         "Labour Lines",
  partsLines:         "Parts",
  materialsLines:     "Materials",
  estimateTotal:      "Estimate Total",
  laborTotal:         "Labour Total",
  partsTotal:         "Parts Total",
  materialsTotal:     "Materials Total",
  approveEstimate:    "Approve Estimate",
  submitToDMS:        "Submit to DMS",
  pendingInspection:  "Pending Inspection",
  inspectionComplete: "Inspection Complete",
  dmsSent:            "Received from DMS",
  addLine:            "Add Line",
  hours:              "hrs",
  loadChecklist:      "Load Full DMS Vehicle Checklist",
  addCustomItem:      "Add Custom Item",
  autoAssign:         "Auto-Assign",
  smartSuggest:       "Smart Suggest",
  bestMatch:          "Best Match",
  smartRecommendation:"Smart Recommendation",
  teamOverview:       "Team Overview",
  active:             "Active",
  idle:               "Idle",
  onBreak:            "On Break",
  absent:             "Absent",
  workshopCapacity:   "Workshop Capacity",
  weeklyHours:        "Weekly Hours",
  shiftHistory:       "Shift History",
  clockedIn:          "Clocked In",
  clockedOut:         "Clocked Out",
  shiftDuration:      "Shift Duration",
  markAllRead:        "Mark All Read",
  noNotifications:    "No notifications yet",
  sortBy:             "Sort by",
  twoLetterCode:      "2-Letter Code",
  fourDigitPin:       "4-Digit PIN",
  invalidCredentials: "Invalid credentials. Please try again.",
  orSignInWith:       "Or Sign in with",
  demoHint:           "Demo: MR + 1234 (Tech) · SV + 5678 (Supervisor) · ET + 1234 (Estimator)",
  make:               "Make",
  model:              "Model",
  customer:           "Customer",
  year:               "Year",
  all:                "All",
  confirm:            "Confirm",
  jobDetail:          "Job Detail",
  technicianStatus:   "Technician Status",
};

type Translations = typeof EN;

const AR: Translations = {
  dashboard:          "لوحة التحكم",
  jobs:               "الوظائف",
  timeRecord:         "سجل الوقت",
  supervision:        "الإشراف المباشر",
  technicians:        "الفنيون",
  workshop:           "الورشة",
  stages:             "المراحل",
  clockIn:            "تسجيل الدخول",
  clockOut:           "تسجيل الخروج",
  startShift:         "بدء الوردية",
  endShift:           "إنهاء الوردية",
  save:               "حفظ",
  cancel:             "إلغاء",
  logout:             "تسجيل الخروج",
  export:             "تصدير",
  assign:             "تعيين",
  reassign:           "إعادة تعيين",
  addNote:            "إضافة ملاحظة",
  notes:              "ملاحظات",
  tasks:              "مهام",
  inspections:        "فحوصات",
  parts:              "قطع غيار",
  subject:            "الموضوع",
  attachment:         "مرفق",
  notifications:      "الإشعارات",
  assignedJobs:       "الوظائف المعيّنة",
  jobManagement:      "إدارة الوظائف",
  allJobs:            "الكل",
  newJobs:            "جديد",
  onHoldJobs:         "معلّق",
  doneJobs:           "منتهي",
  unassigned:         "غير مُعيَّن",
  assignJob:          "تعيين وظيفة",
  viewAllJobs:        "عرض جميع الوظائف",
  putOnHold:          "تعليق",
  resumeJob:          "استئناف",
  moveTo:             "الانتقال إلى",
  advanceStage:       "تقدم المرحلة",
  awaitingQC:         "تمت المهام — تقديم المرحلة تلقائياً",
  allTasksDoneQC:     "تمت جميع المهام — في انتظار مراقبة الجودة",
  qcRequired:         "مراقبة الجودة مطلوبة",
  qcManual:           "فحص الجودة — يجب أن يوافق المشرف قبل المتابعة",
  stageComplete:      "تم الوصول إلى المرحلة الأخيرة — جاهز للإتمام",
  pending:            "قيد الانتظار",
  inProgress:         "قيد التنفيذ",
  onHold:             "معلّق",
  completed:          "مكتمل",
  done:               "تم",
  pass:               "ناجح",
  fail:               "فاشل",
  reception:          "الاستقبال",
  diagnosis:          "التشخيص",
  repair:             "الإصلاح",
  qcCheck:            "مراقبة الجودة",
  readyForDelivery:   "جاهز للتسليم",
  totalHours:         "إجمالي الساعات",
  productivity:       "الإنتاجية",
  workedHours:        "الساعات المعمولة",
  estimatedHours:     "الساعات المقدّرة",
  efficiency:         "الكفاءة",
  vehicle:            "المركبة",
  licensePlate:       "لوحة الترخيص",
  serviceAdvisor:     "مستشار الخدمة",
  odometer:           "عداد المسافة",
  customerNotes:      "ملاحظات العميل",
  laborType:          "نوع العمل",
  attendance:         "الحضور",
  search:             "بحث",
  takeAction:         "اتخاذ إجراء",
  language:           "اللغة",
  settings:           "الإعدادات",
  workshopLoading:    "تحميل الورشة",
  technicianLoad:     "عبء الفني",
  jobPipeline:        "خط أنابيب الوظائف",
  team:               "الفريق",
  capacity:           "السعة",
  criticalAlerts:     "تنبيهات حرجة",
  capacityWarnings:   "تحذيرات السعة",
  fullyBooked:        "محجوز بالكامل",
  nearlyFull:         "شبه ممتلئ",
  available:          "متاح",
  busy:               "مشغول",
  delayed:            "متأخر",
  overdue:            "متأخر عن الموعد",
  today:              "اليوم",
  week:               "الأسبوع",
  month:              "الشهر",
  noJobs:             "لا وظائف",
  signIn:             "تسجيل الدخول",
  welcome:            "مرحباً",
  myWorkingPattern:   "نمط عملي",
  activeJobs:         "الوظائف النشطة",
  openJobs:           "الوظائف المفتوحة",

  attention:          "انتباه",
  estimator:          "المُقدِّر",
  estimates:          "التقديرات",
  estimate:           "التقدير",
  estimateNo:         "رقم التقدير",
  beginInspection:    "بدء الفحص",
  aiDamageAnalysis:   "تحليل الأضرار بالذكاء الاصطناعي",
  takePhoto:          "التقاط صورة",
  retakePhoto:        "إعادة التقاط",
  analysingDamage:    "جاري تحليل الأضرار...",
  damageDescription:  "وصف الضرر",
  laborLines:         "بنود العمالة",
  partsLines:         "قطع الغيار",
  materialsLines:     "المواد",
  estimateTotal:      "إجمالي التقدير",
  laborTotal:         "إجمالي العمالة",
  partsTotal:         "إجمالي القطع",
  materialsTotal:     "إجمالي المواد",
  approveEstimate:    "اعتماد التقدير",
  submitToDMS:        "إرسال إلى النظام",
  pendingInspection:  "فحص معلّق",
  inspectionComplete: "اكتمل الفحص",
  dmsSent:            "مُستلَم من النظام",
  addLine:            "إضافة بند",
  hours:              "ساعة",
  loadChecklist:      "تحميل قائمة فحص المركبة الكاملة",
  addCustomItem:      "إضافة بند مخصص",
  autoAssign:         "تعيين تلقائي",
  smartSuggest:       "اقتراح ذكي",
  bestMatch:          "الأفضل تطابقاً",
  smartRecommendation:"توصية ذكية",
  teamOverview:       "نظرة عامة على الفريق",
  active:             "نشط",
  idle:               "خامل",
  onBreak:            "في استراحة",
  absent:             "غائب",
  workshopCapacity:   "طاقة الورشة",
  weeklyHours:        "ساعات الأسبوع",
  shiftHistory:       "سجل الوردية",
  clockedIn:          "تم التسجيل",
  clockedOut:         "تم الخروج",
  shiftDuration:      "مدة الوردية",
  markAllRead:        "تحديد الكل كمقروء",
  noNotifications:    "لا توجد إشعارات بعد",
  sortBy:             "ترتيب حسب",
  twoLetterCode:      "رمز حرفين",
  fourDigitPin:       "رقم سري 4 أرقام",
  invalidCredentials: "بيانات غير صحيحة. حاول مجدداً.",
  orSignInWith:       "أو سجل الدخول بـ",
  demoHint:           "تجريبي: MR + 1234 (فني) · SV + 5678 (مشرف) · ET + 1234 (مُقدِّر)",
  make:               "الشركة",
  model:              "الموديل",
  customer:           "العميل",
  year:               "السنة",
  all:                "الكل",
  confirm:            "تأكيد",
  jobDetail:          "تفاصيل الوظيفة",
  technicianStatus:   "حالة الفني",
};

const ES: Translations = {
  dashboard:          "Panel",
  jobs:               "Trabajos",
  timeRecord:         "Registro de tiempo",
  supervision:        "Supervisión en vivo",
  technicians:        "Técnicos",
  workshop:           "Taller",
  stages:             "Etapas",
  clockIn:            "Registrar entrada",
  clockOut:           "Registrar salida",
  startShift:         "Iniciar turno",
  endShift:           "Terminar turno",
  save:               "Guardar",
  cancel:             "Cancelar",
  logout:             "Cerrar sesión",
  export:             "Exportar",
  assign:             "Asignar",
  reassign:           "Reasignar",
  addNote:            "Agregar nota",
  notes:              "Notas",
  tasks:              "Tareas",
  inspections:        "Inspecciones",
  parts:              "Piezas",
  subject:            "Asunto",
  attachment:         "Adjunto",
  notifications:      "Notificaciones",
  assignedJobs:       "Trabajos asignados",
  jobManagement:      "Gestión de trabajos",
  allJobs:            "Todos",
  newJobs:            "Nuevo",
  onHoldJobs:         "En espera",
  doneJobs:           "Hecho",
  unassigned:         "Sin asignar",
  assignJob:          "Asignar trabajo",
  viewAllJobs:        "Ver todos los trabajos",
  putOnHold:          "Poner en espera",
  resumeJob:          "Reanudar",
  moveTo:             "Mover a",
  advanceStage:       "Avanzar etapa",
  awaitingQC:         "Todas las tareas listas — avanzando etapa",
  allTasksDoneQC:     "Todas las tareas completadas — esperando control de calidad",
  qcRequired:         "Control de calidad requerido",
  qcManual:           "Control de calidad — el supervisor debe aprobar antes de avanzar",
  stageComplete:      "Etapa final alcanzada — listo para completar",
  pending:            "Pendiente",
  inProgress:         "En progreso",
  onHold:             "En espera",
  completed:          "Completado",
  done:               "Hecho",
  pass:               "Aprobado",
  fail:               "Fallido",
  reception:          "Recepción",
  diagnosis:          "Diagnóstico",
  repair:             "Reparación",
  qcCheck:            "Control de calidad",
  readyForDelivery:   "Listo para entrega",
  totalHours:         "Total de horas",
  productivity:       "Productividad",
  workedHours:        "Horas trabajadas",
  estimatedHours:     "Horas estimadas",
  efficiency:         "Eficiencia",
  vehicle:            "Vehículo",
  licensePlate:       "Matrícula",
  serviceAdvisor:     "Asesor de servicio",
  odometer:           "Odómetro",
  customerNotes:      "Notas del cliente",
  laborType:          "Tipo de trabajo",
  attendance:         "Asistencia",
  search:             "Buscar",
  takeAction:         "Tomar acción",
  language:           "Idioma",
  settings:           "Configuración",
  workshopLoading:    "Carga del taller",
  technicianLoad:     "Carga del técnico",
  jobPipeline:        "Flujo de trabajos",
  team:               "Equipo",
  capacity:           "Capacidad",
  criticalAlerts:     "Alertas críticas",
  capacityWarnings:   "Advertencias de capacidad",
  fullyBooked:        "Completamente ocupado",
  nearlyFull:         "Casi lleno",
  available:          "Disponible",
  busy:               "Ocupado",
  delayed:            "Retrasado",
  overdue:            "Vencido",
  today:              "Hoy",
  week:               "Semana",
  month:              "Mes",
  noJobs:             "Sin trabajos",
  signIn:             "Iniciar sesión",
  welcome:            "Bienvenido",
  myWorkingPattern:   "Mi patrón de trabajo",
  activeJobs:         "Trabajos activos",
  openJobs:           "Trabajos abiertos",

  attention:          "Atención",
  estimator:          "Estimador",
  estimates:          "Estimaciones",
  estimate:           "Estimación",
  estimateNo:         "N.º de estimación",
  beginInspection:    "Iniciar inspección",
  aiDamageAnalysis:   "Análisis de daños con IA",
  takePhoto:          "Tomar foto",
  retakePhoto:        "Repetir foto",
  analysingDamage:    "Analizando daños...",
  damageDescription:  "Descripción del daño",
  laborLines:         "Líneas de mano de obra",
  partsLines:         "Piezas",
  materialsLines:     "Materiales",
  estimateTotal:      "Total estimado",
  laborTotal:         "Total mano de obra",
  partsTotal:         "Total piezas",
  materialsTotal:     "Total materiales",
  approveEstimate:    "Aprobar estimación",
  submitToDMS:        "Enviar al DMS",
  pendingInspection:  "Inspección pendiente",
  inspectionComplete: "Inspección completada",
  dmsSent:            "Recibido del DMS",
  addLine:            "Añadir línea",
  hours:              "h",
  loadChecklist:      "Cargar lista de verificación completa",
  addCustomItem:      "Añadir elemento personalizado",
  autoAssign:         "Asignación automática",
  smartSuggest:       "Sugerencia inteligente",
  bestMatch:          "Mejor coincidencia",
  smartRecommendation:"Recomendación inteligente",
  teamOverview:       "Resumen del equipo",
  active:             "Activo",
  idle:               "Inactivo",
  onBreak:            "En descanso",
  absent:             "Ausente",
  workshopCapacity:   "Capacidad del taller",
  weeklyHours:        "Horas semanales",
  shiftHistory:       "Historial de turno",
  clockedIn:          "Entrada registrada",
  clockedOut:         "Salida registrada",
  shiftDuration:      "Duración del turno",
  markAllRead:        "Marcar todo como leído",
  noNotifications:    "Sin notificaciones aún",
  sortBy:             "Ordenar por",
  twoLetterCode:      "Código de 2 letras",
  fourDigitPin:       "PIN de 4 dígitos",
  invalidCredentials: "Credenciales inválidas. Inténtelo de nuevo.",
  orSignInWith:       "O iniciar sesión con",
  demoHint:           "Demo: MR + 1234 (Técnico) · SV + 5678 (Supervisor) · ET + 1234 (Estimador)",
  make:               "Marca",
  model:              "Modelo",
  customer:           "Cliente",
  year:               "Año",
  all:                "Todos",
  confirm:            "Confirmar",
  jobDetail:          "Detalle del trabajo",
  technicianStatus:   "Estado del técnico",
};

const BS: Translations = {
  dashboard:          "Kontrolna ploča",
  jobs:               "Poslovi",
  timeRecord:         "Evidencija vremena",
  supervision:        "Nadzor uživo",
  technicians:        "Tehničari",
  workshop:           "Radionica",
  stages:             "Faze",
  clockIn:            "Prijava na posao",
  clockOut:           "Odjava s posla",
  startShift:         "Počni smjenu",
  endShift:           "Završi smjenu",
  save:               "Sačuvaj",
  cancel:             "Otkaži",
  logout:             "Odjava",
  export:             "Izvoz",
  assign:             "Dodijeli",
  reassign:           "Ponovni dodjeli",
  addNote:            "Dodaj bilješku",
  notes:              "Bilješke",
  tasks:              "Zadaci",
  inspections:        "Pregledi",
  parts:              "Dijelovi",
  subject:            "Predmet",
  attachment:         "Prilog",
  notifications:      "Obavijesti",
  assignedJobs:       "Dodijeljeni poslovi",
  jobManagement:      "Upravljanje poslovima",
  allJobs:            "Sve",
  newJobs:            "Novo",
  onHoldJobs:         "Na čekanju",
  doneJobs:           "Završeno",
  unassigned:         "Nedodijeljen",
  assignJob:          "Dodijeli posao",
  viewAllJobs:        "Svi poslovi",
  putOnHold:          "Stavi na čekanje",
  resumeJob:          "Nastavi posao",
  moveTo:             "Premjesti u",
  advanceStage:       "Napreduj fazu",
  awaitingQC:         "Svi zadaci gotovi — faza se pomiče automatski",
  allTasksDoneQC:     "Svi zadaci završeni — čeka se kontrola kvaliteta",
  qcRequired:         "Potrebna kontrola kvaliteta",
  qcManual:           "Provjera kvaliteta — nadzornik mora odobriti prije napretka",
  stageComplete:      "Dostigla se posljednja faza — spreman za završetak",
  pending:            "Na čekanju",
  inProgress:         "U toku",
  onHold:             "Na čekanju",
  completed:          "Završeno",
  done:               "Gotovo",
  pass:               "Prolaz",
  fail:               "Pad",
  reception:          "Prijem",
  diagnosis:          "Dijagnoza",
  repair:             "Popravak",
  qcCheck:            "Kontrola kvaliteta",
  readyForDelivery:   "Spreman za isporuku",
  totalHours:         "Ukupno sati",
  productivity:       "Produktivnost",
  workedHours:        "Odrađeni sati",
  estimatedHours:     "Procijenjeni sati",
  efficiency:         "Efikasnost",
  vehicle:            "Vozilo",
  licensePlate:       "Registarska tablica",
  serviceAdvisor:     "Servisni savjetnik",
  odometer:           "Odometar",
  customerNotes:      "Napomene klijenta",
  laborType:          "Vrsta rada",
  attendance:         "Prisustvo",
  search:             "Pretraži",
  takeAction:         "Poduzmi akciju",
  language:           "Jezik",
  settings:           "Postavke",
  workshopLoading:    "Opterećenje radionice",
  technicianLoad:     "Opterećenje tehničara",
  jobPipeline:        "Tok poslova",
  team:               "Tim",
  capacity:           "Kapacitet",
  criticalAlerts:     "Kritična upozorenja",
  capacityWarnings:   "Upozorenja kapaciteta",
  fullyBooked:        "Potpuno zauzeto",
  nearlyFull:         "Skoro puno",
  available:          "Slobodno",
  busy:               "Zauzeto",
  delayed:            "Zakašnjelo",
  overdue:            "Prekoračilo rok",
  today:              "Danas",
  week:               "Sedmica",
  month:              "Mjesec",
  noJobs:             "Nema poslova",
  signIn:             "Prijavi se",
  welcome:            "Dobrodošli",
  myWorkingPattern:   "Moj obrazac rada",
  activeJobs:         "Aktivni poslovi",
  openJobs:           "Otvoreni poslovi",

  attention:          "Pažnja",
  estimator:          "Procjenitelj",
  estimates:          "Procjene",
  estimate:           "Procjena",
  estimateNo:         "Br. procjene",
  beginInspection:    "Počni pregled",
  aiDamageAnalysis:   "AI analiza štete",
  takePhoto:          "Fotografiraj",
  retakePhoto:        "Ponovi fotografiju",
  analysingDamage:    "Analiza štete u toku...",
  damageDescription:  "Opis štete",
  laborLines:         "Linije rada",
  partsLines:         "Dijelovi",
  materialsLines:     "Materijali",
  estimateTotal:      "Ukupna procjena",
  laborTotal:         "Ukupno rad",
  partsTotal:         "Ukupno dijelovi",
  materialsTotal:     "Ukupno materijali",
  approveEstimate:    "Odobri procjenu",
  submitToDMS:        "Pošalji u DMS",
  pendingInspection:  "Pregled na čekanju",
  inspectionComplete: "Pregled završen",
  dmsSent:            "Primljeno iz DMS-a",
  addLine:            "Dodaj liniju",
  hours:              "h",
  loadChecklist:      "Učitaj punu listu pregleda vozila",
  addCustomItem:      "Dodaj prilagođenu stavku",
  autoAssign:         "Automatski dodijeli",
  smartSuggest:       "Pametni prijedlog",
  bestMatch:          "Najbolje podudaranje",
  smartRecommendation:"Pametna preporuka",
  teamOverview:       "Pregled tima",
  active:             "Aktivan",
  idle:               "Slobodan",
  onBreak:            "Na pauzi",
  absent:             "Odsutan",
  workshopCapacity:   "Kapacitet radionice",
  weeklyHours:        "Sedmični sati",
  shiftHistory:       "Historija smjene",
  clockedIn:          "Prijavljen",
  clockedOut:         "Odjavljen",
  shiftDuration:      "Trajanje smjene",
  markAllRead:        "Označi sve kao pročitano",
  noNotifications:    "Još nema obavijesti",
  sortBy:             "Sortiraj po",
  twoLetterCode:      "Dvoslovni kod",
  fourDigitPin:       "PIN od 4 cifre",
  invalidCredentials: "Nevažeće vjerodajnice. Pokušajte ponovo.",
  orSignInWith:       "Ili prijavite se s",
  demoHint:           "Demo: MR + 1234 (Tehničar) · SV + 5678 (Nadzornik) · ET + 1234 (Procjenitelj)",
  make:               "Marka",
  model:              "Model",
  customer:           "Klijent",
  year:               "Godina",
  all:                "Sve",
  confirm:            "Potvrdi",
  jobDetail:          "Detalji posla",
  technicianStatus:   "Status tehničara",
};

const NO: Translations = {
  dashboard:          "Kontrollpanel",
  jobs:               "Jobber",
  timeRecord:         "Tidsregistrering",
  supervision:        "Direkteovervåking",
  technicians:        "Teknikere",
  workshop:           "Verksted",
  stages:             "Stadier",
  clockIn:            "Sjekk inn",
  clockOut:           "Sjekk ut",
  startShift:         "Start skift",
  endShift:           "Avslutt skift",
  save:               "Lagre",
  cancel:             "Avbryt",
  logout:             "Logg ut",
  export:             "Eksporter",
  assign:             "Tildel",
  reassign:           "Tildel på nytt",
  addNote:            "Legg til notat",
  notes:              "Notater",
  tasks:              "Oppgaver",
  inspections:        "Inspeksjoner",
  parts:              "Deler",
  subject:            "Emne",
  attachment:         "Vedlegg",
  notifications:      "Varsler",
  assignedJobs:       "Tildelte jobber",
  jobManagement:      "Jobstyring",
  allJobs:            "Alle",
  newJobs:            "Nye",
  onHoldJobs:         "På vent",
  doneJobs:           "Ferdig",
  unassigned:         "Ikke tildelt",
  assignJob:          "Tildel jobb",
  viewAllJobs:        "Se alle jobber",
  putOnHold:          "Sett på vent",
  resumeJob:          "Gjenoppta",
  moveTo:             "Flytt til",
  advanceStage:       "Avanser stadie",
  awaitingQC:         "Alle oppgaver fullført — avanserer stadie",
  allTasksDoneQC:     "Alle oppgaver fullført — venter på kvalitetskontroll",
  qcRequired:         "Kvalitetskontroll kreves",
  qcManual:           "Kvalitetssjekk — overordnet må godkjenne før videre",
  stageComplete:      "Siste stadium nådd — klar til å fullføre",
  pending:            "Venter",
  inProgress:         "Pågår",
  onHold:             "På vent",
  completed:          "Fullført",
  done:               "Ferdig",
  pass:               "Bestått",
  fail:               "Ikke bestått",
  reception:          "Mottak",
  diagnosis:          "Diagnose",
  repair:             "Reparasjon",
  qcCheck:            "Kvalitetskontroll",
  readyForDelivery:   "Klar for levering",
  totalHours:         "Totalt timer",
  productivity:       "Produktivitet",
  workedHours:        "Arbeidede timer",
  estimatedHours:     "Estimerte timer",
  efficiency:         "Effektivitet",
  vehicle:            "Kjøretøy",
  licensePlate:       "Registreringsnummer",
  serviceAdvisor:     "Servicerådgiver",
  odometer:           "Kilometerstand",
  customerNotes:      "Kundenotater",
  laborType:          "Arbeidstype",
  attendance:         "Oppmøte",
  search:             "Søk",
  takeAction:         "Ta handling",
  language:           "Språk",
  settings:           "Innstillinger",
  workshopLoading:    "Verkstedbelastning",
  technicianLoad:     "Teknikerbelastning",
  jobPipeline:        "Jobbflyt",
  team:               "Team",
  capacity:           "Kapasitet",
  criticalAlerts:     "Kritiske varsler",
  capacityWarnings:   "Kapasitetsadvarsler",
  fullyBooked:        "Fullt booket",
  nearlyFull:         "Nesten fullt",
  available:          "Tilgjengelig",
  busy:               "Opptatt",
  delayed:            "Forsinket",
  overdue:            "Overskredet",
  today:              "I dag",
  week:               "Uke",
  month:              "Måned",
  noJobs:             "Ingen jobber",
  signIn:             "Logg inn",
  welcome:            "Velkommen",
  myWorkingPattern:   "Mitt arbeidsmønster",
  activeJobs:         "Aktive jobber",
  openJobs:           "Åpne jobber",

  attention:          "Oppmerksomhet",
  estimator:          "Estimatør",
  estimates:          "Estimater",
  estimate:           "Estimat",
  estimateNo:         "Estimat nr.",
  beginInspection:    "Start inspeksjon",
  aiDamageAnalysis:   "AI skadeanalyse",
  takePhoto:          "Ta bilde",
  retakePhoto:        "Ta nytt bilde",
  analysingDamage:    "Analyserer skade...",
  damageDescription:  "Skadbeskrivelse",
  laborLines:         "Arbeidslinjer",
  partsLines:         "Deler",
  materialsLines:     "Materialer",
  estimateTotal:      "Totalt estimat",
  laborTotal:         "Arbeid totalt",
  partsTotal:         "Deler totalt",
  materialsTotal:     "Materialer totalt",
  approveEstimate:    "Godkjenn estimat",
  submitToDMS:        "Send til DMS",
  pendingInspection:  "Venter på inspeksjon",
  inspectionComplete: "Inspeksjon fullført",
  dmsSent:            "Mottatt fra DMS",
  addLine:            "Legg til linje",
  hours:              "t",
  loadChecklist:      "Last inn full kjøretøysjekkliste",
  addCustomItem:      "Legg til tilpasset element",
  autoAssign:         "Automatisk tildeling",
  smartSuggest:       "Smart forslag",
  bestMatch:          "Beste treff",
  smartRecommendation:"Smart anbefaling",
  teamOverview:       "Teamoversikt",
  active:             "Aktiv",
  idle:               "Ledig",
  onBreak:            "I pause",
  absent:             "Fraværende",
  workshopCapacity:   "Verkstedkapasitet",
  weeklyHours:        "Ukentlige timer",
  shiftHistory:       "Skifthistorikk",
  clockedIn:          "Sjekket inn",
  clockedOut:         "Sjekket ut",
  shiftDuration:      "Skiftvarighet",
  markAllRead:        "Merk alt som lest",
  noNotifications:    "Ingen varsler ennå",
  sortBy:             "Sorter etter",
  twoLetterCode:      "2-bokstavskode",
  fourDigitPin:       "4-sifret PIN",
  invalidCredentials: "Ugyldig legitimasjon. Prøv igjen.",
  orSignInWith:       "Eller logg inn med",
  demoHint:           "Demo: MR + 1234 (Tekniker) · SV + 5678 (Overordnet) · ET + 1234 (Estimatør)",
  make:               "Merke",
  model:              "Modell",
  customer:           "Kunde",
  year:               "År",
  all:                "Alle",
  confirm:            "Bekreft",
  jobDetail:          "Jobbdetaljer",
  technicianStatus:   "Teknikerstatus",
};

const TRANSLATIONS: Record<LangCode, Translations> = { en: EN, ar: AR, es: ES, bs: BS, no: NO };

interface LanguageContextValue {
  lang: LangCode;
  t: Translations;
  rtl: boolean;
  setLang: (lang: LangCode) => void;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("en");

  useEffect(() => {
    AsyncStorage.getItem("igmma_lang").then((saved) => {
      if (saved && LANGUAGES[saved as LangCode]) setLangState(saved as LangCode);
    });
  }, []);

  const setLang = useCallback(async (code: LangCode) => {
    await AsyncStorage.setItem("igmma_lang", code);
    setLangState(code);
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, t: TRANSLATIONS[lang], rtl: LANGUAGES[lang].rtl, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be inside LanguageProvider");
  return ctx;
}
