import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type LangCode = "en" | "ar" | "es" | "bs" | "no";

export const LANGUAGES: Record<LangCode, { label: string; nativeLabel: string; flag: string; rtl: boolean }> = {
  en: { label: "English",   nativeLabel: "English",   flag: "🇬🇧", rtl: false },
  ar: { label: "Arabic",    nativeLabel: "العربية",   flag: "🇦🇪", rtl: true  },
  es: { label: "Spanish",   nativeLabel: "Español",   flag: "🇪🇸", rtl: false },
  bs: { label: "Bosnian",   nativeLabel: "Bosanski",  flag: "🇧🇦", rtl: false },
  no: { label: "Norwegian", nativeLabel: "Norsk",     flag: "🇳🇴", rtl: false },
};

const EN = {
  dashboard:          "Dashboard",
  jobs:               "Jobs",
  timeRecord:         "Time Record",
  supervision:        "Live Supervision",
  technicians:        "Technicians",
  workshop:           "Workshop",
  stages:             "Stages",
  clockIn:            "Clock In",
  clockOut:           "Clock Out",
  startShift:         "Start Shift",
  endShift:           "End Shift",
  save:               "Save",
  cancel:             "Cancel",
  logout:             "Logout",
  export:             "Export",
  assign:             "Assign",
  reassign:           "Reassign",
  addNote:            "Add Note",
  notes:              "Notes",
  tasks:              "Tasks",
  inspections:        "Inspections",
  parts:              "Parts",
  subject:            "Subject",
  attachment:         "Attachment",
  notifications:      "Notifications",
  assignedJobs:       "Assigned Jobs",
  jobManagement:      "Job Management",
  allJobs:            "All",
  newJobs:            "New",
  onHoldJobs:         "On Hold",
  doneJobs:           "Done",
  unassigned:         "Unassigned",
  assignJob:          "Assign Job",
  viewAllJobs:        "View All Jobs",
  putOnHold:          "Put On Hold",
  resumeJob:          "Resume Job",
  moveTo:             "Move to",
  advanceStage:       "Advance Stage",
  awaitingQC:         "All tasks done — advancing stage",
  allTasksDoneQC:     "All tasks done — awaiting QC approval",
  qcRequired:         "QC Required",
  qcManual:           "Quality check — supervisor must approve before advancing",
  stageComplete:      "Final stage reached — ready to complete job",
  pending:            "Pending",
  inProgress:         "In Progress",
  onHold:             "On Hold",
  completed:          "Completed",
  done:               "Done",
  pass:               "Pass",
  fail:               "Fail",
  reception:          "Reception",
  diagnosis:          "Diagnosis",
  repair:             "Repair",
  qcCheck:            "QC Check",
  readyForDelivery:   "Ready for Delivery",
  totalHours:         "Total Hours",
  productivity:       "Productivity",
  workedHours:        "Worked",
  estimatedHours:     "Est. Hours",
  efficiency:         "Efficiency",
  vehicle:            "Vehicle",
  licensePlate:       "License Plate",
  serviceAdvisor:     "Service Advisor",
  odometer:           "Odometer",
  customerNotes:      "Customer Notes",
  laborType:          "Labor Type",
  attendance:         "Attendance",
  search:             "Search",
  takeAction:         "Take Action",
  language:           "Language",
  settings:           "Settings",
  workshopLoading:    "Workshop Loading",
  technicianLoad:     "Technician Load",
  jobPipeline:        "Job Pipeline",
  team:               "Team",
  capacity:           "Capacity",
  criticalAlerts:     "Critical Alerts",
  capacityWarnings:   "Capacity Warnings",
  fullyBooked:        "Fully Booked",
  nearlyFull:         "Nearly Full",
  available:          "Available",
  busy:               "Busy",
  delayed:            "Delayed",
  overdue:            "Overdue",
  today:              "Today",
  week:               "Week",
  month:              "Month",
  noJobs:             "No jobs",
  signIn:             "Sign In",
  welcome:            "Welcome",
  myWorkingPattern:   "My Working Pattern",
  activeJobs:         "Active Jobs",
  openJobs:           "Open Jobs",
};

type Translations = typeof EN;

const AR: Translations = {
  dashboard:          "لوحة التحكم",
  jobs:               "الوظائف",
  timeRecord:         "سجل الوقت",
  supervision:        "الإشراف المباشر",
  technicians:        "الفنيون",
  workshop:           "الورشة",
  stages:             "المراحل",
  clockIn:            "تسجيل الدخول",
  clockOut:           "تسجيل الخروج",
  startShift:         "بدء الوردية",
  endShift:           "إنهاء الوردية",
  save:               "حفظ",
  cancel:             "إلغاء",
  logout:             "تسجيل الخروج",
  export:             "تصدير",
  assign:             "تعيين",
  reassign:           "إعادة تعيين",
  addNote:            "إضافة ملاحظة",
  notes:              "ملاحظات",
  tasks:              "مهام",
  inspections:        "فحوصات",
  parts:              "قطع غيار",
  subject:            "الموضوع",
  attachment:         "مرفق",
  notifications:      "الإشعارات",
  assignedJobs:       "الوظائف المعيّنة",
  jobManagement:      "إدارة الوظائف",
  allJobs:            "الكل",
  newJobs:            "جديد",
  onHoldJobs:         "معلّق",
  doneJobs:           "منتهي",
  unassigned:         "غير مُعيَّن",
  assignJob:          "تعيين وظيفة",
  viewAllJobs:        "عرض جميع الوظائف",
  putOnHold:          "تعليق",
  resumeJob:          "استئناف",
  moveTo:             "الانتقال إلى",
  advanceStage:       "تقدم المرحلة",
  awaitingQC:         "تمت المهام — تقديم المرحلة تلقائياً",
  allTasksDoneQC:     "تمت جميع المهام — في انتظار مراقبة الجودة",
  qcRequired:         "مراقبة الجودة مطلوبة",
  qcManual:           "فحص الجودة — يجب أن يوافق المشرف قبل المتابعة",
  stageComplete:      "تم الوصول إلى المرحلة الأخيرة — جاهز للإتمام",
  pending:            "قيد الانتظار",
  inProgress:         "قيد التنفيذ",
  onHold:             "معلّق",
  completed:          "مكتمل",
  done:               "تم",
  pass:               "ناجح",
  fail:               "فاشل",
  reception:          "الاستقبال",
  diagnosis:          "التشخيص",
  repair:             "الإصلاح",
  qcCheck:            "مراقبة الجودة",
  readyForDelivery:   "جاهز للتسليم",
  totalHours:         "إجمالي الساعات",
  productivity:       "الإنتاجية",
  workedHours:        "الساعات المعمولة",
  estimatedHours:     "الساعات المقدّرة",
  efficiency:         "الكفاءة",
  vehicle:            "المركبة",
  licensePlate:       "لوحة الترخيص",
  serviceAdvisor:     "مستشار الخدمة",
  odometer:           "عداد المسافة",
  customerNotes:      "ملاحظات العميل",
  laborType:          "نوع العمل",
  attendance:         "الحضور",
  search:             "بحث",
  takeAction:         "اتخاذ إجراء",
  language:           "اللغة",
  settings:           "الإعدادات",
  workshopLoading:    "تحميل الورشة",
  technicianLoad:     "عبء الفني",
  jobPipeline:        "خط أنابيب الوظائف",
  team:               "الفريق",
  capacity:           "السعة",
  criticalAlerts:     "تنبيهات حرجة",
  capacityWarnings:   "تحذيرات السعة",
  fullyBooked:        "محجوز بالكامل",
  nearlyFull:         "شبه ممتلئ",
  available:          "متاح",
  busy:               "مشغول",
  delayed:            "متأخر",
  overdue:            "متأخر عن الموعد",
  today:              "اليوم",
  week:               "الأسبوع",
  month:              "الشهر",
  noJobs:             "لا وظائف",
  signIn:             "تسجيل الدخول",
  welcome:            "مرحباً",
  myWorkingPattern:   "نمط عملي",
  activeJobs:         "الوظائف النشطة",
  openJobs:           "الوظائف المفتوحة",
};

const ES: Translations = {
  dashboard:          "Panel",
  jobs:               "Trabajos",
  timeRecord:         "Registro de tiempo",
  supervision:        "Supervisión en vivo",
  technicians:        "Técnicos",
  workshop:           "Taller",
  stages:             "Etapas",
  clockIn:            "Registrar entrada",
  clockOut:           "Registrar salida",
  startShift:         "Iniciar turno",
  endShift:           "Terminar turno",
  save:               "Guardar",
  cancel:             "Cancelar",
  logout:             "Cerrar sesión",
  export:             "Exportar",
  assign:             "Asignar",
  reassign:           "Reasignar",
  addNote:            "Agregar nota",
  notes:              "Notas",
  tasks:              "Tareas",
  inspections:        "Inspecciones",
  parts:              "Piezas",
  subject:            "Asunto",
  attachment:         "Adjunto",
  notifications:      "Notificaciones",
  assignedJobs:       "Trabajos asignados",
  jobManagement:      "Gestión de trabajos",
  allJobs:            "Todos",
  newJobs:            "Nuevo",
  onHoldJobs:         "En espera",
  doneJobs:           "Hecho",
  unassigned:         "Sin asignar",
  assignJob:          "Asignar trabajo",
  viewAllJobs:        "Ver todos los trabajos",
  putOnHold:          "Poner en espera",
  resumeJob:          "Reanudar",
  moveTo:             "Mover a",
  advanceStage:       "Avanzar etapa",
  awaitingQC:         "Todas las tareas listas — avanzando etapa",
  allTasksDoneQC:     "Todas las tareas completadas — esperando control de calidad",
  qcRequired:         "Control de calidad requerido",
  qcManual:           "Control de calidad — el supervisor debe aprobar antes de avanzar",
  stageComplete:      "Etapa final alcanzada — listo para completar",
  pending:            "Pendiente",
  inProgress:         "En progreso",
  onHold:             "En espera",
  completed:          "Completado",
  done:               "Hecho",
  pass:               "Aprobado",
  fail:               "Fallido",
  reception:          "Recepción",
  diagnosis:          "Diagnóstico",
  repair:             "Reparación",
  qcCheck:            "Control de calidad",
  readyForDelivery:   "Listo para entrega",
  totalHours:         "Total de horas",
  productivity:       "Productividad",
  workedHours:        "Horas trabajadas",
  estimatedHours:     "Horas estimadas",
  efficiency:         "Eficiencia",
  vehicle:            "Vehículo",
  licensePlate:       "Matrícula",
  serviceAdvisor:     "Asesor de servicio",
  odometer:           "Odómetro",
  customerNotes:      "Notas del cliente",
  laborType:          "Tipo de trabajo",
  attendance:         "Asistencia",
  search:             "Buscar",
  takeAction:         "Tomar acción",
  language:           "Idioma",
  settings:           "Configuración",
  workshopLoading:    "Carga del taller",
  technicianLoad:     "Carga del técnico",
  jobPipeline:        "Flujo de trabajos",
  team:               "Equipo",
  capacity:           "Capacidad",
  criticalAlerts:     "Alertas críticas",
  capacityWarnings:   "Advertencias de capacidad",
  fullyBooked:        "Completamente ocupado",
  nearlyFull:         "Casi lleno",
  available:          "Disponible",
  busy:               "Ocupado",
  delayed:            "Retrasado",
  overdue:            "Vencido",
  today:              "Hoy",
  week:               "Semana",
  month:              "Mes",
  noJobs:             "Sin trabajos",
  signIn:             "Iniciar sesión",
  welcome:            "Bienvenido",
  myWorkingPattern:   "Mi patrón de trabajo",
  activeJobs:         "Trabajos activos",
  openJobs:           "Trabajos abiertos",
};

const BS: Translations = {
  dashboard:          "Kontrolna ploča",
  jobs:               "Poslovi",
  timeRecord:         "Evidencija vremena",
  supervision:        "Nadzor uživo",
  technicians:        "Tehničari",
  workshop:           "Radionica",
  stages:             "Faze",
  clockIn:            "Prijava na posao",
  clockOut:           "Odjava s posla",
  startShift:         "Počni smjenu",
  endShift:           "Završi smjenu",
  save:               "Sačuvaj",
  cancel:             "Otkaži",
  logout:             "Odjava",
  export:             "Izvoz",
  assign:             "Dodijeli",
  reassign:           "Ponovni dodjeli",
  addNote:            "Dodaj bilješku",
  notes:              "Bilješke",
  tasks:              "Zadaci",
  inspections:        "Pregledi",
  parts:              "Dijelovi",
  subject:            "Predmet",
  attachment:         "Prilog",
  notifications:      "Obavijesti",
  assignedJobs:       "Dodijeljeni poslovi",
  jobManagement:      "Upravljanje poslovima",
  allJobs:            "Sve",
  newJobs:            "Novo",
  onHoldJobs:         "Na čekanju",
  doneJobs:           "Završeno",
  unassigned:         "Nedodijeljen",
  assignJob:          "Dodijeli posao",
  viewAllJobs:        "Svi poslovi",
  putOnHold:          "Stavi na čekanje",
  resumeJob:          "Nastavi posao",
  moveTo:             "Premjesti u",
  advanceStage:       "Napreduj fazu",
  awaitingQC:         "Svi zadaci gotovi — faza se pomiče automatski",
  allTasksDoneQC:     "Svi zadaci završeni — čeka se kontrola kvaliteta",
  qcRequired:         "Potrebna kontrola kvaliteta",
  qcManual:           "Provjera kvaliteta — nadzornik mora odobriti prije napretka",
  stageComplete:      "Dostigla se posljednja faza — spreman za završetak",
  pending:            "Na čekanju",
  inProgress:         "U toku",
  onHold:             "Na čekanju",
  completed:          "Završeno",
  done:               "Gotovo",
  pass:               "Prolaz",
  fail:               "Pad",
  reception:          "Prijem",
  diagnosis:          "Dijagnoza",
  repair:             "Popravak",
  qcCheck:            "Kontrola kvaliteta",
  readyForDelivery:   "Spreman za isporuku",
  totalHours:         "Ukupno sati",
  productivity:       "Produktivnost",
  workedHours:        "Odrađeni sati",
  estimatedHours:     "Procijenjeni sati",
  efficiency:         "Efikasnost",
  vehicle:            "Vozilo",
  licensePlate:       "Registarska tablica",
  serviceAdvisor:     "Servisni savjetnik",
  odometer:           "Odometar",
  customerNotes:      "Napomene klijenta",
  laborType:          "Vrsta rada",
  attendance:         "Prisustvo",
  search:             "Pretraži",
  takeAction:         "Poduzmi akciju",
  language:           "Jezik",
  settings:           "Postavke",
  workshopLoading:    "Opterećenje radionice",
  technicianLoad:     "Opterećenje tehničara",
  jobPipeline:        "Tok poslova",
  team:               "Tim",
  capacity:           "Kapacitet",
  criticalAlerts:     "Kritična upozorenja",
  capacityWarnings:   "Upozorenja kapaciteta",
  fullyBooked:        "Potpuno zauzeto",
  nearlyFull:         "Skoro puno",
  available:          "Slobodno",
  busy:               "Zauzeto",
  delayed:            "Zakašnjelo",
  overdue:            "Prekoračilo rok",
  today:              "Danas",
  week:               "Sedmica",
  month:              "Mjesec",
  noJobs:             "Nema poslova",
  signIn:             "Prijavi se",
  welcome:            "Dobrodošli",
  myWorkingPattern:   "Moj obrazac rada",
  activeJobs:         "Aktivni poslovi",
  openJobs:           "Otvoreni poslovi",
};

const NO: Translations = {
  dashboard:          "Kontrollpanel",
  jobs:               "Jobber",
  timeRecord:         "Tidsregistrering",
  supervision:        "Direkteovervåking",
  technicians:        "Teknikere",
  workshop:           "Verksted",
  stages:             "Stadier",
  clockIn:            "Sjekk inn",
  clockOut:           "Sjekk ut",
  startShift:         "Start skift",
  endShift:           "Avslutt skift",
  save:               "Lagre",
  cancel:             "Avbryt",
  logout:             "Logg ut",
  export:             "Eksporter",
  assign:             "Tildel",
  reassign:           "Tildel på nytt",
  addNote:            "Legg til notat",
  notes:              "Notater",
  tasks:              "Oppgaver",
  inspections:        "Inspeksjoner",
  parts:              "Deler",
  subject:            "Emne",
  attachment:         "Vedlegg",
  notifications:      "Varsler",
  assignedJobs:       "Tildelte jobber",
  jobManagement:      "Jobstyring",
  allJobs:            "Alle",
  newJobs:            "Nye",
  onHoldJobs:         "På vent",
  doneJobs:           "Ferdig",
  unassigned:         "Ikke tildelt",
  assignJob:          "Tildel jobb",
  viewAllJobs:        "Se alle jobber",
  putOnHold:          "Sett på vent",
  resumeJob:          "Gjenoppta",
  moveTo:             "Flytt til",
  advanceStage:       "Avanser stadie",
  awaitingQC:         "Alle oppgaver fullført — avanserer stadie",
  allTasksDoneQC:     "Alle oppgaver fullført — venter på kvalitetskontroll",
  qcRequired:         "Kvalitetskontroll kreves",
  qcManual:           "Kvalitetssjekk — overordnet må godkjenne før videre",
  stageComplete:      "Siste stadium nådd — klar til å fullføre",
  pending:            "Venter",
  inProgress:         "Pågår",
  onHold:             "På vent",
  completed:          "Fullført",
  done:               "Ferdig",
  pass:               "Bestått",
  fail:               "Ikke bestått",
  reception:          "Mottak",
  diagnosis:          "Diagnose",
  repair:             "Reparasjon",
  qcCheck:            "Kvalitetskontroll",
  readyForDelivery:   "Klar for levering",
  totalHours:         "Totalt timer",
  productivity:       "Produktivitet",
  workedHours:        "Arbeidede timer",
  estimatedHours:     "Estimerte timer",
  efficiency:         "Effektivitet",
  vehicle:            "Kjøretøy",
  licensePlate:       "Registreringsnummer",
  serviceAdvisor:     "Servicerådgiver",
  odometer:           "Kilometerstand",
  customerNotes:      "Kundenotater",
  laborType:          "Arbeidstype",
  attendance:         "Oppmøte",
  search:             "Søk",
  takeAction:         "Ta handling",
  language:           "Språk",
  settings:           "Innstillinger",
  workshopLoading:    "Verkstedbelastning",
  technicianLoad:     "Teknikerbelastning",
  jobPipeline:        "Jobbflyt",
  team:               "Team",
  capacity:           "Kapasitet",
  criticalAlerts:     "Kritiske varsler",
  capacityWarnings:   "Kapasitetsadvarsler",
  fullyBooked:        "Fullt booket",
  nearlyFull:         "Nesten fullt",
  available:          "Tilgjengelig",
  busy:               "Opptatt",
  delayed:            "Forsinket",
  overdue:            "Overskredet",
  today:              "I dag",
  week:               "Uke",
  month:              "Måned",
  noJobs:             "Ingen jobber",
  signIn:             "Logg inn",
  welcome:            "Velkommen",
  myWorkingPattern:   "Mitt arbeidsmønster",
  activeJobs:         "Aktive jobber",
  openJobs:           "Åpne jobber",
};

const TRANSLATIONS: Record<LangCode, Translations> = { en: EN, ar: AR, es: ES, bs: BS, no: NO };

interface LanguageContextValue {
  lang: LangCode;
  t: Translations;
  rtl: boolean;
  setLang: (lang: LangCode) => void;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("en");

  useEffect(() => {
    AsyncStorage.getItem("igmma_lang").then((saved) => {
      if (saved && LANGUAGES[saved as LangCode]) setLangState(saved as LangCode);
    });
  }, []);

  const setLang = useCallback(async (code: LangCode) => {
    await AsyncStorage.setItem("igmma_lang", code);
    setLangState(code);
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, t: TRANSLATIONS[lang], rtl: LANGUAGES[lang].rtl, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be inside LanguageProvider");
  return ctx;
}
