import { Router, type IRouter } from "express";
import estimatesRouter from "./estimates";
import storageRouter from "./storage";
import healthRouter from "./health";
import yardAuthRouter from "./yard-auth";
import yardLocationsRouter from "./yard-locations";
import yardSpotsRouter from "./yard-spots";
import yardVehiclesRouter from "./yard-vehicles";
import yardInspectionsRouter from "./yard-inspections";
import yardDashboardRouter from "./yard-dashboard";
import yardRecommendationsRouter from "./yard-recommendations";
import yardUsersRouter from "./yard-users";
import yardTransfersRouter from "./yard-transfers";
import partsRouter from "./parts";
import jobsRouter from "./jobs";
import techniciansRouter from "./technicians";
import servicePackagesRouter from "./service-packages";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(estimatesRouter);
router.use(yardAuthRouter);
router.use(yardLocationsRouter);
router.use(yardSpotsRouter);
router.use(yardVehiclesRouter);
router.use(yardInspectionsRouter);
router.use(yardDashboardRouter);
router.use(yardRecommendationsRouter);
router.use(yardUsersRouter);
router.use(yardTransfersRouter);
router.use(partsRouter);
router.use(jobsRouter);
router.use(techniciansRouter);
router.use(servicePackagesRouter);
router.use(adminRouter);

export default router;
